<?php

/**
 * @file
 * This module holds functions for twitteroauth.
 */

use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_theme().
 *
 * @return array
 *   Theme variables.
 */
function twitteroauth_theme() {
  return [
    'twitteroauth_content' => [
      'variables' => [
        'display_text' => NULL,
        'name' => NULL,
        'tweet_link' => NULL,
        'media_url' => NULL,
        'screen_name' => NULL,
        'created_at' => NULL,
        'result_index' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_block_view_alter().
 */
function twitteroauth_block_view_alter(array &$build, BlockPluginInterface $block) {
  if (strpos($block->getPluginId(), 'block_content') !== FALSE) {
    $entity = \Drupal::service('entity.repository')->loadEntityByUuid('block_content', $block->getDerivativeId());
    if (!empty($entity) && $entity->bundle() == 'twitteroauth_search') {
      $build['#_entity'] = $entity;
      $build['#pre_render'][] = '_twitteroauth_pre_render_fetchtweets';
    }
  }
}

/**
 * Pre render callback to fetch twitter data.
 *
 * @param array $build
 *   The build.
 *
 * @return mixed
 *   The build.
 */
function _twitteroauth_pre_render_fetchtweets(array $build) {
  if (!empty($build['#_entity'])) {
    $build['content']['tweet_content'] = [
      '#lazy_builder' => [
        'twitteroauth.tweet_fetcher:fetch',
      [
        $build['#_entity']->field_twitteroauth_tweet_count->value,
        trim($build['#_entity']->field_twitteroauth_search_query->value),
        $build['#_entity']->field_twitteroauth_display_media->value,
        $build['#_entity']->field_twitteroauth_expiration->value,
      ],
      ],
      '#create_placeholder' => FALSE,
    ];
  }

  return $build;
}
